spring.application.name=PhishingStats

spring.data.mongodb.uri = mongodb+srv://yashbest1234_db_user:NkijN0UaEvaF8bWS@cluster0.aewunvr.mongodb.net/?appName=Cluster0
spring.data.mongodb.database = Phishings